import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Hero from "../components/Hero";
import Categories from "../components/Categories";
import Bestsellers from "../components/Bestsellers";
import Featured from "../components/Featured";
import News from "../components/News";
import Testimonials from "../components/Testimonials";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hung Feet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Hero />
      <Categories />
      <Bestsellers />
      <Featured />
      <News />
      <Testimonials />
      <Footer />
    </div>
  );
}
